[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "pandas>=2.3.1",
    "passlib>=1.7.4",
    "plotly>=6.2.0",
    "pyyaml>=6.0.2",
    "streamlit>=1.47.1",
]
